"""Registers KitchenPlace, a "place" task generated by scripts/create_task.py.

Importing this module has the side effect of registering KitchenPlace with
robosuite's REGISTERED_ENVS (via robosuite's EnvMeta), so it must be
imported before robosuite.make() is called with this env name.
"""
from robocasa.environments.kitchen.kitchen import *


class KitchenPlace(Kitchen):
    """Pick up an object from one fixture and place it on/in another.

    Generated from the "place" template -- mirrors robocasa's own
    PickPlaceCounterToCabinet
    (robocasa/environments/kitchen/atomic/kitchen_pick_place.py).
    """

    DEFAULT_OBJ_GROUPS = ['cube']

    def __init__(self, obj_groups=DEFAULT_OBJ_GROUPS, exclude_obj_groups=None, *args, **kwargs):
        self.obj_groups = obj_groups
        self.exclude_obj_groups = exclude_obj_groups
        super().__init__(*args, **kwargs)

    def _setup_kitchen_references(self):
        super()._setup_kitchen_references()
        self.dest = self.register_fixture_ref("dest", dict(id=FixtureType.CABINET))
        self.source = self.register_fixture_ref(
            "source", dict(id=FixtureType.ISLAND, ref=self.dest)
        )
        self.init_robot_base_ref = self.dest

    def _setup_scene(self):
        super()._setup_scene()
        self.dest.open_door(env=self)

    def get_ep_meta(self):
        ep_meta = super().get_ep_meta()
        obj_lang = self.get_obj_lang()
        ep_meta["lang"] = f"Pick the {obj_lang} from the island and place it on the cabinet."
        return ep_meta

    def _get_obj_cfgs(self):
        cfgs = []
        cfgs.append(
            dict(
                name="obj",
                obj_groups=self.obj_groups,
                exclude_obj_groups=self.exclude_obj_groups,
                graspable=True,
                placement=dict(
                    fixture=self.source,
                    sample_region_kwargs=dict(ref=self.dest),
                    size=(0.60, 0.30),
                    pos=("ref", -1.0),
                    offset=(0.0, 0.10),
                ),
            )
        )
        return cfgs

    def _check_success(self):
        obj_inside_dest = OU.obj_inside_of(self, "obj", self.dest)
        gripper_obj_far = OU.gripper_obj_far(self)
        return obj_inside_dest and gripper_obj_far
