#!/usr/bin/env python3
"""Creates a new RoboCasa task for emdb_simulator -- interactively (for
humans) or via flags (for scripts/agents).

Generates emdb_simulator/core/<snake_case>_task.py from one of three
templates ("lift", "place", or "custom") and registers it by appending an
import line to emdb_simulator/core/registered_tasks.py. See
docs/source/howto/creating_tasks.md (human guide) or docs/source/llms.md
(machine-oriented reference, including the "custom" freeform scaffold for
composite/multi-object tasks) for background.

Interactive:
    python3 scripts/create_task.py

Non-interactive -- passing --name switches modes and skips all prompts:
    python3 scripts/create_task.py --name PlaceMugInSink --template place \\
        --source COUNTER --dest CABINET --obj-groups mug --json

    python3 scripts/create_task.py --name MakeIceLemonade --template custom --json
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from string import Template

CORE_DIR = Path(__file__).resolve().parents[1] / "emdb_simulator" / "core"
REPO_ROOT = CORE_DIR.parents[1]
REGISTRY_PATH = CORE_DIR / "registered_tasks.py"
REGISTRY_MARKER = "# --- new tasks are appended below this line by scripts/create_task.py ---"

# Curated subset of robocasa.models.fixtures.fixture.FixtureType relevant to
# object placement. Extend this list if you need a fixture that isn't here.
FIXTURES = [
    "ISLAND",
    "COUNTER",
    "DINING_COUNTER",
    "CABINET",
    "DRAWER",
    "SHELF",
    "SINK",
    "MICROWAVE",
    "STOVE",
    "FRIDGE",
    "DISHWASHER",
]

# Fixtures with a door that must be opened in _setup_scene for a placed
# object to be reachable/checkable -- mirrors robocasa's own
# PickPlaceCounterTo* task variants.
DOOR_FIXTURES = {"CABINET", "DRAWER", "MICROWAVE", "DISHWASHER"}

DEFAULT_OBJ_GROUPS = ["straw", "peeler", "sugar_cube", "shrimp"]

TEMPLATES = [
    ("lift", "lift - pick up an object and raise it above a height threshold"),
    ("place", "place - move an object from one fixture to another"),
    ("custom", "custom - freeform scaffold for composite/multi-object tasks (advanced -- you write _get_obj_cfgs/_check_success by hand afterward)"),
]

LIFT_TEMPLATE = Template(
    '''"""Registers $class_name, a "lift" task generated by scripts/create_task.py.

Importing this module has the side effect of registering $class_name with
robosuite's REGISTERED_ENVS (via robosuite's EnvMeta), so it must be
imported before robosuite.make() is called with this env name.
"""
from robocasa.environments.kitchen.kitchen import *


class $class_name(Kitchen):
    """Pick up an object and raise it above a height threshold.

    Generated from the "lift" template -- mirrors KitchenLift
    (emdb_simulator/core/kitchen_lift_task.py).
    """

    LIFT_HEIGHT = $height  # meters above starting height counted as "lifted"

    DEFAULT_OBJ_GROUPS = $obj_groups_repr

    def __init__(self, obj_groups=DEFAULT_OBJ_GROUPS, exclude_obj_groups=None, *args, **kwargs):
        self.obj_groups = obj_groups
        self.exclude_obj_groups = exclude_obj_groups
        self._obj_start_z = None
        super().__init__(*args, **kwargs)

    def _setup_kitchen_references(self):
        super()._setup_kitchen_references()
        self.spawn_fixture = self.register_fixture_ref(
            "spawn_fixture", dict(id=FixtureType.$fixture)
        )
        self.init_robot_base_ref = self.spawn_fixture

    def get_ep_meta(self):
        ep_meta = super().get_ep_meta()
        obj_lang = self.get_obj_lang()
        ep_meta["lang"] = $lang_expr
        return ep_meta

    def _get_obj_cfgs(self):
        cfgs = []
        cfgs.append(
            dict(
                name="obj",
                obj_groups=self.obj_groups,
                exclude_obj_groups=self.exclude_obj_groups,
                graspable=True,
                init_robot_here=True,
                placement=dict(
                    fixture=self.spawn_fixture,
                    size=(0.40, 0.40),
                    pos=(0, -1.0),
                ),
            )
        )
        return cfgs

    def _reset_internal(self):
        super()._reset_internal()
        self._obj_start_z = self.sim.data.body_xpos[self.obj_body_id["obj"]][2]

    def _check_success(self):
        if self._obj_start_z is None:
            return False
        obj_z = self.sim.data.body_xpos[self.obj_body_id["obj"]][2]
        return (obj_z - self._obj_start_z) > self.LIFT_HEIGHT
'''
)

PLACE_TEMPLATE = Template(
    '''"""Registers $class_name, a "place" task generated by scripts/create_task.py.

Importing this module has the side effect of registering $class_name with
robosuite's REGISTERED_ENVS (via robosuite's EnvMeta), so it must be
imported before robosuite.make() is called with this env name.
"""
from robocasa.environments.kitchen.kitchen import *


class $class_name(Kitchen):
    """Pick up an object from one fixture and place it on/in another.

    Generated from the "place" template -- mirrors robocasa's own
    PickPlaceCounterToCabinet
    (robocasa/environments/kitchen/atomic/kitchen_pick_place.py).
    """

    DEFAULT_OBJ_GROUPS = $obj_groups_repr

    def __init__(self, obj_groups=DEFAULT_OBJ_GROUPS, exclude_obj_groups=None, *args, **kwargs):
        self.obj_groups = obj_groups
        self.exclude_obj_groups = exclude_obj_groups
        super().__init__(*args, **kwargs)

    def _setup_kitchen_references(self):
        super()._setup_kitchen_references()
        self.dest = self.register_fixture_ref("dest", dict(id=FixtureType.$dest_fixture))
        self.source = self.register_fixture_ref(
            "source", dict(id=FixtureType.$source_fixture, ref=self.dest)
        )
        self.init_robot_base_ref = self.dest
$setup_scene_override
    def get_ep_meta(self):
        ep_meta = super().get_ep_meta()
        obj_lang = self.get_obj_lang()
        ep_meta["lang"] = $lang_expr
        return ep_meta

    def _get_obj_cfgs(self):
        cfgs = []
        cfgs.append(
            dict(
                name="obj",
                obj_groups=self.obj_groups,
                exclude_obj_groups=self.exclude_obj_groups,
                graspable=True,
                placement=dict(
                    fixture=self.source,
                    sample_region_kwargs=dict(ref=self.dest),
                    size=(0.60, 0.30),
                    pos=("ref", -1.0),
                    offset=(0.0, 0.10),
                ),
            )
        )
        return cfgs

    def _check_success(self):
        obj_inside_dest = OU.obj_inside_of(self, "obj", self.dest)
        gripper_obj_far = OU.gripper_obj_far(self)
        return obj_inside_dest and gripper_obj_far
'''
)

# Freeform scaffold for multi-object/multi-fixture/multi-stage ("composite")
# tasks that don't fit the lift/place shape -- see docs/source/llms.md for
# the object_utils (OU) vocabulary and pointers to real composite examples
# under misc/robocasa/robocasa/environments/kitchen/composite/. Intended for
# an LLM/agent to fill in, not for the interactive wizard's target audience.
CUSTOM_TEMPLATE = Template(
    '''"""Registers $class_name, a custom task scaffolded by scripts/create_task.py.

Importing this module has the side effect of registering $class_name with
robosuite's REGISTERED_ENVS (via robosuite's EnvMeta), so it must be
imported before robosuite.make() is called with this env name.

This is a freeform scaffold (--template custom), not the "lift"/"place"
templates -- fill in the TODOs below. For real multi-object/multi-fixture
examples, read 1-2 files under
misc/robocasa/robocasa/environments/kitchen/composite/<activity>/*.py in
this repo before writing _get_obj_cfgs/_check_success -- don't guess the
robocasa API. See docs/source/llms.md for a summary of the
robocasa.utils.object_utils (OU) helpers used there.
"""
from robocasa.environments.kitchen.kitchen import *


class $class_name(Kitchen):
    """TODO: one-line summary of what this task does.

    TODO: numbered steps, mirroring robocasa's own composite task
    docstrings (see misc/robocasa/robocasa/environments/kitchen/composite/).
    """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    def _setup_kitchen_references(self):
        super()._setup_kitchen_references()
        # TODO: register every fixture this task needs, e.g.:
        #   self.fridge = self.register_fixture_ref("fridge", dict(id=FixtureType.FRIDGE))
        #   self.counter = self.register_fixture_ref(
        #       "counter", dict(id=FixtureType.COUNTER, ref=self.fridge)
        #   )
        # self.init_robot_base_ref = self.<one of the fixtures above>
        raise NotImplementedError("TODO: register fixtures and set init_robot_base_ref")

    def get_ep_meta(self):
        ep_meta = super().get_ep_meta()
        ep_meta["lang"] = $lang_expr
        return ep_meta

    def _get_obj_cfgs(self):
        # TODO: return a list of dicts, one per object. Common keys: name,
        # obj_groups, exclude_obj_groups, graspable, object_scale,
        # init_robot_here, placement=dict(fixture=..., object=...,
        # sample_region_kwargs=dict(ref=...), size=(w, h), pos=(x, y),
        # offset=(dx, dy)).
        raise NotImplementedError("TODO: return a list of object config dicts")

    def _check_success(self):
        # TODO: combine robocasa.utils.object_utils (imported as OU) helpers,
        # e.g. OU.obj_inside_of, OU.check_obj_in_receptacle,
        # OU.check_obj_fixture_contact, OU.gripper_obj_far,
        # self.check_contact(objA, objB).
        raise NotImplementedError("TODO: return True when the task is solved")
'''
)


# --- small shared helpers ---------------------------------------------------


def prompt(question, default=None):
    suffix = f" [{default}]" if default is not None else ""
    while True:
        answer = input(f"{question}{suffix}: ").strip()
        if answer:
            return answer
        if default is not None:
            return default
        print("This field is required.")


def prompt_choice(question, options, default_index=0):
    """options: list of str, or list of (token, label) tuples. Returns the token."""
    pairs = [(o, o) if isinstance(o, str) else o for o in options]
    print(question)
    for i, (_token, label) in enumerate(pairs, start=1):
        marker = "  (default)" if i - 1 == default_index else ""
        print(f"  {i}) {label}{marker}")
    while True:
        raw = input("> ").strip()
        if not raw:
            return pairs[default_index][0]
        if raw.isdigit() and 1 <= int(raw) <= len(pairs):
            return pairs[int(raw) - 1][0]
        print(f"Enter a number between 1 and {len(pairs)}.")


def to_snake_case(name):
    return re.sub(r"(?<!^)(?=[A-Z])", "_", name).lower()


def validate_class_name(name):
    """Returns (module_name, error); error is None when name is valid and free."""
    if not re.fullmatch(r"[A-Z][A-Za-z0-9]*", name or ""):
        return None, f"Task name {name!r} must start with an uppercase letter and contain only letters/digits."
    module_name = to_snake_case(name) + "_task"
    target = CORE_DIR / f"{module_name}.py"
    if target.exists():
        return None, f"{target} already exists -- pick a different name."
    return module_name, None


def validate_fixture(name, field):
    if name not in FIXTURES:
        return f"{field} {name!r} is not a known fixture. Valid choices: {', '.join(FIXTURES)}."
    return None


def lang_expr_for(description, default_expr):
    if not description:
        return default_expr
    return repr(description)


def register_task(module_name, class_name):
    if not REGISTRY_PATH.exists():
        raise SystemExit(f"Registry file not found: {REGISTRY_PATH}")
    text = REGISTRY_PATH.read_text()
    if REGISTRY_MARKER not in text:
        raise SystemExit(
            f"Marker line not found in {REGISTRY_PATH} -- restore it before running this wizard."
        )
    if f"import {module_name}" in text:
        return
    import_line = f"from emdb_simulator.core import {module_name}  # noqa: F401  registers {class_name}\n"
    with REGISTRY_PATH.open("a") as f:
        f.write(import_line)


def fail(errors, as_json):
    if as_json:
        print(json.dumps({"ok": False, "errors": errors}))
    else:
        for e in errors:
            print(f"ERROR: {e}", file=sys.stderr)
    return 1


# --- interactive wizard ------------------------------------------------------


def prompt_class_name():
    while True:
        name = prompt("Task class name (PascalCase, e.g. PlaceMugInSink)")
        module_name, error = validate_class_name(name)
        if error:
            print(error)
            continue
        return name, module_name


def prompt_obj_groups():
    raw = prompt(
        "Object group(s) to spawn, comma-separated (keep them small -- the "
        "project's gripper jaw only opens ~31mm)",
        default=",".join(DEFAULT_OBJ_GROUPS),
    )
    return [g.strip() for g in raw.split(",") if g.strip()]


def run_interactive():
    print("=== emdb_simulator task creation wizard ===\n")

    class_name, module_name = prompt_class_name()
    template = prompt_choice("\nTemplate:", TEMPLATES)

    if template == "lift":
        obj_groups = prompt_obj_groups()
        fixture = prompt_choice("\nFixture to spawn the object on:", FIXTURES, default_index=FIXTURES.index("ISLAND"))
        height = prompt("\nHeight in meters the object must be raised to count as lifted", default="0.10")
        default_lang = 'f"Pick up and lift the {obj_lang}."'
        description = prompt(
            "\nOne-line task description for the episode instruction (leave blank for a sensible default)",
            default="",
        )
        lang_expr = lang_expr_for(description, default_lang)
        source = LIFT_TEMPLATE.substitute(
            class_name=class_name, height=height, obj_groups_repr=repr(obj_groups), fixture=fixture, lang_expr=lang_expr
        )
        summary = f"template=lift fixture={fixture} height={height} obj_groups={obj_groups}"
    elif template == "place":
        obj_groups = prompt_obj_groups()
        source_fixture = prompt_choice(
            "\nSource fixture (where the object starts):", FIXTURES, default_index=FIXTURES.index("COUNTER")
        )
        dest_fixture = prompt_choice(
            "\nDestination fixture (where the object must end up):", FIXTURES, default_index=FIXTURES.index("CABINET")
        )
        source_words = source_fixture.lower().replace("_", " ")
        dest_words = dest_fixture.lower().replace("_", " ")
        default_lang = f'f"Pick the {{obj_lang}} from the {source_words} and place it on the {dest_words}."'
        description = prompt(
            "\nOne-line task description for the episode instruction (leave blank for a sensible default)",
            default="",
        )
        lang_expr = lang_expr_for(description, default_lang)
        setup_scene_override = ""
        if dest_fixture in DOOR_FIXTURES:
            setup_scene_override = (
                "\n    def _setup_scene(self):\n"
                "        super()._setup_scene()\n"
                "        self.dest.open_door(env=self)\n"
            )
        source = PLACE_TEMPLATE.substitute(
            class_name=class_name,
            obj_groups_repr=repr(obj_groups),
            source_fixture=source_fixture,
            dest_fixture=dest_fixture,
            setup_scene_override=setup_scene_override,
            lang_expr=lang_expr,
        )
        summary = f"template=place source={source_fixture} dest={dest_fixture} obj_groups={obj_groups}"
    else:  # custom
        description = prompt(
            "\nOne-line task description (optional -- you'll fill in the real logic by hand)",
            default="",
        )
        lang_expr = lang_expr_for(description, '"TODO: describe the task in one sentence."')
        source = CUSTOM_TEMPLATE.substitute(class_name=class_name, lang_expr=lang_expr)
        summary = "template=custom (freeform scaffold -- edit _setup_kitchen_references/_get_obj_cfgs/_check_success by hand)"

    target = CORE_DIR / f"{module_name}.py"
    print(f"\nAbout to write {target} ({summary}).")
    confirm = prompt("Proceed? [y/N]", default="n")
    if confirm.lower() not in ("y", "yes"):
        print("Aborted, nothing was written.")
        return

    target.write_text(source)
    register_task(module_name, class_name)

    print(f"\nWrote {target}")
    print(f"Registered {class_name} in {REGISTRY_PATH}")
    print("\nNext steps:")
    print(f"  ros2 run emdb_simulator scene_loader --ros-args -p task:={class_name}")
    print("(colcon build --symlink-install means no rebuild is needed for this pure-Python change)")


# --- non-interactive / agent-driven mode -------------------------------------


def run_noninteractive(args):
    errors = []
    module_name, name_err = validate_class_name(args.name)
    if name_err:
        errors.append(name_err)

    if args.template not in ("lift", "place", "custom"):
        errors.append(f"--template must be 'lift', 'place', or 'custom', got {args.template!r}.")
        return fail(errors, args.json)

    height = None
    fixture = None
    source_fixture = None
    dest_fixture = None

    if args.template == "lift":
        fixture = args.fixture or "ISLAND"
        err = validate_fixture(fixture, "--fixture")
        if err:
            errors.append(err)
        try:
            height = float(args.height) if args.height is not None else 0.10
        except ValueError:
            errors.append(f"--height must be a number, got {args.height!r}.")
    elif args.template == "place":
        source_fixture = args.source or "COUNTER"
        dest_fixture = args.dest or "CABINET"
        for val, field in ((source_fixture, "--source"), (dest_fixture, "--dest")):
            err = validate_fixture(val, field)
            if err:
                errors.append(err)

    if errors:
        return fail(errors, args.json)

    if args.template == "lift":
        obj_groups = [g.strip() for g in (args.obj_groups or ",".join(DEFAULT_OBJ_GROUPS)).split(",") if g.strip()]
        default_lang = 'f"Pick up and lift the {obj_lang}."'
        lang_expr = lang_expr_for(args.lang, default_lang)
        source = LIFT_TEMPLATE.substitute(
            class_name=args.name, height=height, obj_groups_repr=repr(obj_groups), fixture=fixture, lang_expr=lang_expr
        )
        meta = {"template": "lift", "fixture": fixture, "height": height}
    elif args.template == "place":
        obj_groups = [g.strip() for g in (args.obj_groups or ",".join(DEFAULT_OBJ_GROUPS)).split(",") if g.strip()]
        source_words = source_fixture.lower().replace("_", " ")
        dest_words = dest_fixture.lower().replace("_", " ")
        default_lang = f'f"Pick the {{obj_lang}} from the {source_words} and place it on the {dest_words}."'
        lang_expr = lang_expr_for(args.lang, default_lang)
        setup_scene_override = ""
        if dest_fixture in DOOR_FIXTURES:
            setup_scene_override = (
                "\n    def _setup_scene(self):\n"
                "        super()._setup_scene()\n"
                "        self.dest.open_door(env=self)\n"
            )
        source = PLACE_TEMPLATE.substitute(
            class_name=args.name,
            obj_groups_repr=repr(obj_groups),
            source_fixture=source_fixture,
            dest_fixture=dest_fixture,
            setup_scene_override=setup_scene_override,
            lang_expr=lang_expr,
        )
        meta = {"template": "place", "source": source_fixture, "dest": dest_fixture}
    else:  # custom
        lang_expr = lang_expr_for(args.lang, '"TODO: describe the task in one sentence."')
        source = CUSTOM_TEMPLATE.substitute(class_name=args.name, lang_expr=lang_expr)
        meta = {"template": "custom"}

    target = CORE_DIR / f"{module_name}.py"

    if args.dry_run:
        if args.json:
            print(json.dumps({"ok": True, "dry_run": True, "file": str(target), "source": source, **meta}))
        else:
            print(source)
        return 0

    target.write_text(source)
    register_task(module_name, args.name)

    result = {
        "ok": True,
        "class_name": args.name,
        "module": module_name,
        "file": str(target.relative_to(REPO_ROOT)),
        "registered_in": str(REGISTRY_PATH.relative_to(REPO_ROOT)),
        "run_command": f"ros2 run emdb_simulator scene_loader --ros-args -p task:={args.name}",
        **meta,
    }
    if args.json:
        print(json.dumps(result))
    else:
        print(f"OK: wrote {result['file']}, registered {args.name} in {result['registered_in']}")
        print(f"Try it: {result['run_command']}")
    return 0


def build_arg_parser():
    p = argparse.ArgumentParser(description="Create a new emdb_simulator task, interactively or via flags.")
    p.add_argument("--name", help="PascalCase task class name. Passing this switches to non-interactive mode.")
    p.add_argument("--template", choices=["lift", "place", "custom"])
    p.add_argument("--obj-groups", help="[lift/place] Comma-separated object groups (default: straw,peeler,sugar_cube,shrimp).")
    p.add_argument("--fixture", help="[lift] Fixture to spawn the object on (default: ISLAND).")
    p.add_argument("--height", help="[lift] Lift height in meters (default: 0.10).")
    p.add_argument("--source", help="[place] Source fixture (default: COUNTER).")
    p.add_argument("--dest", help="[place] Destination fixture (default: CABINET).")
    p.add_argument("--lang", help="One-line episode description (optional; a sensible default is used otherwise).")
    p.add_argument("--dry-run", action="store_true", help="Print the generated file instead of writing it.")
    p.add_argument("--json", action="store_true", help="Emit a single JSON result line instead of prose.")
    return p


def main():
    args = build_arg_parser().parse_args()
    if args.name:
        if not args.template:
            sys.exit(fail(["--template is required (lift or place) when using --name."], args.json))
        sys.exit(run_noninteractive(args))
    run_interactive()


if __name__ == "__main__":
    try:
        main()
    except (KeyboardInterrupt, EOFError):
        print("\nAborted.")
        sys.exit(1)
