#!/usr/bin/env python3
"""List, inspect, edit, preview, and create robots for emdb_simulator --
interactively (for humans) or via subcommands (for scripts/agents).

List/Inspect/Edit/Create work with plain Python 3, no ROS2/robosuite
environment needed. "Preview a robot in 3D" needs `source env.sh` first
(it builds a real robosuite env to render). See
docs/source/howto/managing_robots.md (human guide) or docs/source/llms.md
(machine-oriented reference) for background.

Interactive menu:
    python3 scripts/robot_tool.py

Non-interactive subcommands:
    python3 scripts/robot_tool.py list [--json]
    python3 scripts/robot_tool.py inspect --robot UR5eOmron [--json]
    python3 scripts/robot_tool.py edit --robot UR5eOmron --param default_gripper --value TwoFG7Gripper [--json]
    python3 scripts/robot_tool.py create --name PandaFixed --arm Panda --base fixed --gripper PandaGripper [--json]
    python3 scripts/robot_tool.py preview --robot UR5eOmron
"""
from __future__ import annotations

import argparse
import ast
import json
import re
import sys
from pathlib import Path
from string import Template

CORE_DIR = Path(__file__).resolve().parents[1] / "emdb_simulator" / "core"
REPO_ROOT = CORE_DIR.parents[1]
REGISTRY_PATH = CORE_DIR / "registered_robots.py"
REGISTRY_MARKER = "# --- new robots are appended below this line by scripts/robot_tool.py ---"

INSPECT_PROPS = [
    "default_base",
    "default_arms",
    "default_gripper",
    "init_qpos",
    "init_torso_qpos",
    "base_xpos_offset",
]
EDITABLE_PROPS = ["default_gripper", "init_qpos"]

# Curated arm base classes, verified against the vendored robosuite source
# under robosuite/models/robots/manipulators/.
ARMS = {
    "UR5e": ("robosuite.models.robots.manipulators.ur5e_robot", "UR5e"),
    "Panda": ("robosuite.models.robots.manipulators.panda_robot", "Panda"),
    "Sawyer": ("robosuite.models.robots.manipulators.sawyer_robot", "Sawyer"),
    "IIWA": ("robosuite.models.robots.manipulators.iiwa_robot", "IIWA"),
    "XArm7": ("robosuite.models.robots.manipulators.xarm7_robot", "XArm7"),
}

# (token, display label, default_base value or None, register_robot_class target)
BASE_CHOICES = [
    ("wheeled", "OmronMobileBase (wheeled)", "OmronMobileBase", "WheeledRobot"),
    ("fixed", "None (fixed base, use the arm's own default)", None, "FixedBaseRobot"),
]

# (token, display label). Token "none" means "don't override default_gripper".
GRIPPER_CHOICES = [
    ("PandaGripper", "PandaGripper"),
    ("Robotiq85Gripper", "Robotiq85Gripper"),
    ("Robotiq140Gripper", "Robotiq140Gripper"),
    ("RobotiqThreeFingerGripper", "RobotiqThreeFingerGripper"),
    ("TwoFG7Gripper", "TwoFG7Gripper (this project's OnRobot 2FG7)"),
    ("none", "None (use the arm's own default gripper)"),
]
EDIT_GRIPPER_NAMES = [
    "PandaGripper",
    "Robotiq85Gripper",
    "Robotiq140Gripper",
    "RobotiqThreeFingerGripper",
    "TwoFG7Gripper",
]

ROBOT_TEMPLATE = Template(
    '''"""Registers $class_name with robosuite, generated by scripts/robot_tool.py.

Importing this module has the side effect of registering $class_name with
robosuite's REGISTERED_ROBOTS / ROBOT_CLASS_MAPPING, so it must be imported
before robosuite.make() is called with this robot name.
"""
$imports_block

@register_robot_class("$target_type")
class $class_name($arm_class):
    """Generated robot ($arm_class arm)."""
$property_blocks
    # base_xpos_offset is arena-specific and needs manual tuning if this
    # robot doesn't spawn well in a scene -- see UR5eOmron in
    # emdb_simulator/core/robot_loader.py for a worked example.
'''
)


# --- small shared helpers ---------------------------------------------------


def prompt(question, default=None):
    suffix = f" [{default}]" if default is not None else ""
    while True:
        answer = input(f"{question}{suffix}: ").strip()
        if answer:
            return answer
        if default is not None:
            return default
        print("This field is required.")


def prompt_choice(question, options, default_index=0):
    """options: list of str, or list of (token, label) tuples. Returns the token."""
    pairs = [(o, o) if isinstance(o, str) else o for o in options]
    print(question)
    for i, (_token, label) in enumerate(pairs, start=1):
        marker = "  (default)" if i - 1 == default_index else ""
        print(f"  {i}) {label}{marker}")
    while True:
        raw = input("> ").strip()
        if not raw:
            return pairs[default_index][0]
        if raw.isdigit() and 1 <= int(raw) <= len(pairs):
            return pairs[int(raw) - 1][0]
        print(f"Enter a number between 1 and {len(pairs)}.")


def to_snake_case(name):
    return re.sub(r"(?<!^)(?=[A-Z])", "_", name).lower()


def parse_floats(raw):
    return [float(v.strip()) for v in raw.split(",")]


def prop_block(name, expr_text):
    return f"\n    @property\n    def {name}(self):\n        return {expr_text}\n"


def fail(errors, as_json):
    if as_json:
        print(json.dumps({"ok": False, "errors": errors}))
    else:
        for e in errors:
            print(f"ERROR: {e}", file=sys.stderr)
    return 1


# --- discovery ------------------------------------------------------------


def find_robot_classes():
    robots = []
    for path in sorted(CORE_DIR.glob("*.py")):
        source = path.read_text()
        try:
            tree = ast.parse(source, filename=str(path))
        except SyntaxError:
            continue
        for node in tree.body:
            if not isinstance(node, ast.ClassDef):
                continue
            target_type = None
            for dec in node.decorator_list:
                if isinstance(dec, ast.Call) and getattr(dec.func, "id", None) == "register_robot_class":
                    if dec.args and isinstance(dec.args[0], ast.Constant):
                        target_type = dec.args[0].value
            if target_type is None:
                continue
            bases = [
                b.id if isinstance(b, ast.Name) else (ast.get_source_segment(source, b) or "?")
                for b in node.bases
            ]
            robots.append(
                {
                    "file": path,
                    "source": source,
                    "node": node,
                    "class_name": node.name,
                    "target_type": target_type,
                    "bases": bases,
                }
            )
    return robots


def find_robot_by_name(robots, name):
    for r in robots:
        if r["class_name"] == name:
            return r
    return None


def get_property_return(class_node, prop_name):
    for item in class_node.body:
        if isinstance(item, ast.FunctionDef) and item.name == prop_name:
            is_property = any(isinstance(d, ast.Name) and d.id == "property" for d in item.decorator_list)
            if not is_property:
                continue
            for stmt in item.body:
                if isinstance(stmt, ast.Return) and stmt.value is not None:
                    return stmt.value
    return None


def robot_properties(robot):
    props = {}
    for prop in INSPECT_PROPS:
        node = get_property_return(robot["node"], prop)
        props[prop] = ast.get_source_segment(robot["source"], node) if node is not None else None
    return props


def choose_robot(robots):
    if not robots:
        print("No registered robots found under emdb_simulator/core/.")
        return None
    options = [(r["class_name"], f"{r['class_name']} ({r['file'].name})") for r in robots]
    name = prompt_choice("\nWhich robot?", options)
    return find_robot_by_name(robots, name)


# --- edit / create logic shared by interactive + CLI paths -------------------


def describe_current(prop, value_node):
    try:
        if prop == "default_gripper":
            return ast.literal_eval(value_node)
        if isinstance(value_node, ast.Call) and value_node.args:
            return ast.literal_eval(value_node.args[0])
    except (ValueError, IndexError):
        pass
    return None


def perform_edit(robot, prop, raw_value):
    value_node = get_property_return(robot["node"], prop)
    if value_node is None:
        return {"ok": False, "error": f"{robot['class_name']} does not override {prop}; nothing to edit."}
    if value_node.lineno != value_node.end_lineno:
        return {
            "ok": False,
            "error": f"{prop} spans multiple lines in {robot['file']}:{value_node.lineno} -- too complex for this tool.",
        }

    if prop == "default_gripper":
        try:
            current = ast.literal_eval(value_node)
        except ValueError:
            current = None
        if not isinstance(current, dict) or len(current) != 1:
            return {
                "ok": False,
                "error": f"default_gripper isn't a simple single-arm dict -- edit {robot['file']}:{value_node.lineno} by hand.",
            }
        if raw_value not in EDIT_GRIPPER_NAMES:
            return {
                "ok": False,
                "error": f"{raw_value!r} is not a known gripper. Valid choices: {', '.join(EDIT_GRIPPER_NAMES)}.",
            }
        key = next(iter(current))
        new_text = '{"' + key + '": "' + raw_value + '"}'
    else:  # init_qpos
        is_np_array = (
            isinstance(value_node, ast.Call)
            and isinstance(value_node.func, ast.Attribute)
            and value_node.func.attr == "array"
            and len(value_node.args) == 1
            and isinstance(value_node.args[0], (ast.List, ast.Tuple))
        )
        if not is_np_array:
            return {
                "ok": False,
                "error": f"init_qpos isn't a plain np.array([...]) literal -- edit {robot['file']}:{value_node.lineno} by hand.",
            }
        try:
            ast.literal_eval(value_node.args[0])
        except ValueError:
            return {"ok": False, "error": f"Couldn't parse current init_qpos -- edit {robot['file']}:{value_node.lineno} by hand."}
        try:
            new_values = parse_floats(raw_value)
        except ValueError:
            return {"ok": False, "error": f"Couldn't parse {raw_value!r} as comma-separated numbers."}
        new_text = "np.array([" + ", ".join(str(v) for v in new_values) + "])"

    lines = robot["source"].splitlines(keepends=True)
    line = lines[value_node.lineno - 1]
    lines[value_node.lineno - 1] = line[: value_node.col_offset] + new_text + line[value_node.end_col_offset :]
    robot["file"].write_text("".join(lines))
    return {"ok": True, "property": prop, "new": new_text, "file": str(robot["file"].relative_to(REPO_ROOT))}


def register_module(module_name, class_name):
    if not REGISTRY_PATH.exists():
        raise SystemExit(f"Registry file not found: {REGISTRY_PATH}")
    text = REGISTRY_PATH.read_text()
    if REGISTRY_MARKER not in text:
        raise SystemExit(f"Marker line not found in {REGISTRY_PATH} -- restore it before running this wizard.")
    if f"import {module_name}" in text:
        return
    import_line = f"from emdb_simulator.core import {module_name}  # noqa: F401  registers {class_name}\n"
    with REGISTRY_PATH.open("a") as f:
        f.write(import_line)


def validate_robot_class_name(name):
    if not re.fullmatch(r"[A-Z][A-Za-z0-9]*", name or ""):
        return None, f"Robot name {name!r} must start with an uppercase letter and contain only letters/digits."
    module_name = to_snake_case(name) + "_robot"
    target = CORE_DIR / f"{module_name}.py"
    if target.exists():
        return None, f"{target} already exists -- pick a different name."
    return module_name, None


def generate_robot_source(class_name, arm_token, base_token, gripper_token, init_qpos_values, init_torso_qpos_values):
    arm_module, arm_class = ARMS[arm_token]
    _display, base_name, target_type = next((d, b, t) for tok, d, b, t in BASE_CHOICES if tok == base_token)
    gripper_name = None
    uses_project_gripper = False
    if gripper_token == "TwoFG7Gripper":
        gripper_name = "TwoFG7Gripper"
        uses_project_gripper = True
    elif gripper_token != "none":
        gripper_name = gripper_token

    imports = []
    if init_qpos_values or init_torso_qpos_values:
        imports.append("import numpy as np\n")
    if uses_project_gripper:
        imports.append(
            "from emdb_simulator.core import gripper_loader  # noqa: F401  registers TwoFG7Gripper with robosuite\n"
        )
    imports.append(f"from {arm_module} import {arm_class}\n")
    imports.append("from robosuite.robots import register_robot_class\n")
    imports_block = "".join(imports)

    blocks = []
    if base_name:
        blocks.append(prop_block("default_base", '"' + base_name + '"'))
    blocks.append(prop_block("default_arms", '{"right": "' + arm_class + '"}'))
    if gripper_name:
        blocks.append(prop_block("default_gripper", '{"right": "' + gripper_name + '"}'))
    if init_qpos_values:
        blocks.append(prop_block("init_qpos", "np.array([" + ", ".join(str(v) for v in init_qpos_values) + "])"))
    if init_torso_qpos_values:
        blocks.append(
            prop_block("init_torso_qpos", "np.array([" + ", ".join(str(v) for v in init_torso_qpos_values) + "])")
        )
    property_blocks = "".join(blocks)

    source = ROBOT_TEMPLATE.substitute(
        class_name=class_name,
        imports_block=imports_block,
        target_type=target_type,
        arm_class=arm_class,
        property_blocks=property_blocks,
    )
    meta = {"arm": arm_token, "base": base_token, "gripper": gripper_token, "target_type": target_type}
    return source, meta


def run_preview(robot):
    try:
        import robosuite
    except ImportError:
        print("robosuite isn't importable -- run `source env.sh` first, then re-run this tool.")
        return 1
    import numpy as np

    from emdb_simulator.core import registered_robots  # noqa: F401  registers all custom robots

    env = robosuite.make(
        env_name="Lift",
        robots=[robot["class_name"]],
        has_renderer=True,
        has_offscreen_renderer=False,
        render_camera=None,
        ignore_done=True,
        use_camera_obs=False,
        control_freq=20,
        renderer="mjviewer",
    )
    env.reset()
    low, _high = env.action_spec
    print("Previewing -- Ctrl+C to stop.")
    try:
        while True:
            env.step(np.zeros_like(low))
            env.render()
    except KeyboardInterrupt:
        pass
    finally:
        env.close()
    return 0


# --- interactive menu actions -------------------------------------------------


def cmd_list(robots):
    if not robots:
        print("No registered robots found under emdb_simulator/core/.")
        return
    print()
    for r in robots:
        print(f"  {r['class_name']}  (extends {', '.join(r['bases'])}, {r['file'].name})")


def cmd_inspect(robots):
    robot = choose_robot(robots)
    if robot is None:
        return
    props = robot_properties(robot)
    print(f"\n{robot['class_name']}  ({robot['file'].relative_to(REPO_ROOT)})")
    print(f"  extends: {', '.join(robot['bases'])}")
    print(f'  register_robot_class target: "{robot["target_type"]}"')
    for prop, text in props.items():
        print(f"  {prop}: {text if text is not None else '(not overridden)'}")


def cmd_edit(robots):
    robot = choose_robot(robots)
    if robot is None:
        return
    prop = prompt_choice("\nWhich parameter to edit?", EDITABLE_PROPS)
    value_node = get_property_return(robot["node"], prop)
    if value_node is None:
        print(f"{robot['class_name']} does not override {prop}; nothing to edit (it uses the arm's default).")
        return
    print(f"Current {prop}: {describe_current(prop, value_node)}")
    if prop == "default_gripper":
        raw_value = prompt_choice("New gripper:", EDIT_GRIPPER_NAMES)
    else:
        raw_value = prompt("New comma-separated init_qpos values")
    result = perform_edit(robot, prop, raw_value)
    print(f"Updated {prop} in {result['file']}." if result["ok"] else result["error"])


def cmd_preview(robots):
    robot = choose_robot(robots)
    if robot is None:
        return
    run_preview(robot)


def prompt_class_name_robot():
    while True:
        name = prompt("New robot class name (PascalCase, e.g. PandaFixed)")
        module_name, error = validate_robot_class_name(name)
        if error:
            print(error)
            continue
        return name, module_name


def cmd_create_robot(_robots):
    print()
    class_name, module_name = prompt_class_name_robot()
    arm_token = prompt_choice("\nArm base class:", list(ARMS.keys()))
    base_token = prompt_choice("\nBase:", [(tok, disp) for tok, disp, _, _ in BASE_CHOICES])
    gripper_token = prompt_choice("\nDefault gripper:", GRIPPER_CHOICES, default_index=len(GRIPPER_CHOICES) - 1)

    init_qpos = None
    if prompt("\nSet a custom init_qpos (joint angles)? [y/N]", default="n").lower() in ("y", "yes"):
        init_qpos = parse_floats(prompt("Comma-separated joint angles (radians)"))

    init_torso_qpos = None
    base_name = next(b for tok, _, b, _ in BASE_CHOICES if tok == base_token)
    if base_name and prompt("\nSet a custom init_torso_qpos (torso lift joint)? [y/N]", default="n").lower() in ("y", "yes"):
        init_torso_qpos = parse_floats(prompt("Comma-separated torso joint value(s)"))

    source, meta = generate_robot_source(class_name, arm_token, base_token, gripper_token, init_qpos, init_torso_qpos)
    target = CORE_DIR / f"{module_name}.py"
    print(f"\nAbout to write {target} ({meta}).")
    if prompt("Proceed? [y/N]", default="n").lower() not in ("y", "yes"):
        print("Aborted, nothing was written.")
        return

    target.write_text(source)
    register_module(module_name, class_name)
    print(f"\nWrote {target}")
    print(f"Registered {class_name} in {REGISTRY_PATH}")
    print("\nNext steps:")
    print(f"  python3 scripts/robot_tool.py preview --robot {class_name}")
    print(f"  ros2 run emdb_simulator scene_loader --ros-args -p robot:={class_name}")


ACTIONS = [
    ("List robots", cmd_list),
    ("Inspect a robot", cmd_inspect),
    ("Edit a robot's parameters", cmd_edit),
    ("Preview a robot in 3D", cmd_preview),
    ("Create a new robot", cmd_create_robot),
]


def run_interactive_menu():
    print("=== emdb_simulator robot tool ===")
    while True:
        print("\nWhat would you like to do?")
        for i, (label, _fn) in enumerate(ACTIONS, start=1):
            print(f"  {i}) {label}")
        print("  0) Quit")
        choice = input("> ").strip()
        if choice in ("0", "q", "quit"):
            break
        if not choice.isdigit() or not (1 <= int(choice) <= len(ACTIONS)):
            print("Unknown option.")
            continue
        _label, fn = ACTIONS[int(choice) - 1]
        fn(find_robot_classes())


# --- non-interactive / agent-driven subcommands -------------------------------


def cli_list(args):
    robots = find_robot_classes()
    items = [
        {"class_name": r["class_name"], "extends": r["bases"], "file": str(r["file"].relative_to(REPO_ROOT))}
        for r in robots
    ]
    if args.json:
        print(json.dumps({"ok": True, "robots": items}))
    else:
        if not items:
            print("No registered robots found under emdb_simulator/core/.")
        for it in items:
            print(f"{it['class_name']}  (extends {', '.join(it['extends'])}, {it['file']})")
    return 0


def cli_inspect(args):
    robots = find_robot_classes()
    robot = find_robot_by_name(robots, args.robot)
    if robot is None:
        return fail([f"No robot named {args.robot!r} found. Run the 'list' subcommand to see available robots."], args.json)
    props = robot_properties(robot)
    if args.json:
        print(
            json.dumps(
                {
                    "ok": True,
                    "class_name": robot["class_name"],
                    "extends": robot["bases"],
                    "target_type": robot["target_type"],
                    "file": str(robot["file"].relative_to(REPO_ROOT)),
                    "properties": props,
                }
            )
        )
    else:
        print(f"{robot['class_name']}  ({robot['file'].relative_to(REPO_ROOT)})")
        print(f"  extends: {', '.join(robot['bases'])}")
        print(f'  register_robot_class target: "{robot["target_type"]}"')
        for prop, text in props.items():
            print(f"  {prop}: {text if text is not None else '(not overridden)'}")
    return 0


def cli_edit(args):
    robots = find_robot_classes()
    robot = find_robot_by_name(robots, args.robot)
    if robot is None:
        return fail([f"No robot named {args.robot!r} found. Run the 'list' subcommand to see available robots."], args.json)
    result = perform_edit(robot, args.param, args.value)
    if args.json:
        print(json.dumps(result))
    elif result["ok"]:
        print(f"OK: updated {result['property']} in {result['file']}")
    else:
        print(f"ERROR: {result['error']}", file=sys.stderr)
    return 0 if result["ok"] else 1


def cli_create(args):
    errors = []
    module_name, name_err = validate_robot_class_name(args.name)
    if name_err:
        errors.append(name_err)

    init_qpos = None
    if args.init_qpos:
        try:
            init_qpos = parse_floats(args.init_qpos)
        except ValueError:
            errors.append(f"--init-qpos must be comma-separated numbers, got {args.init_qpos!r}.")

    init_torso_qpos = None
    if args.init_torso_qpos:
        try:
            init_torso_qpos = parse_floats(args.init_torso_qpos)
        except ValueError:
            errors.append(f"--init-torso-qpos must be comma-separated numbers, got {args.init_torso_qpos!r}.")
        if args.base != "wheeled":
            errors.append("--init-torso-qpos only makes sense with --base wheeled.")

    if errors:
        return fail(errors, args.json)

    source, meta = generate_robot_source(args.name, args.arm, args.base, args.gripper, init_qpos, init_torso_qpos)
    target = CORE_DIR / f"{module_name}.py"

    if args.dry_run:
        if args.json:
            print(json.dumps({"ok": True, "dry_run": True, "file": str(target), "source": source, **meta}))
        else:
            print(source)
        return 0

    target.write_text(source)
    register_module(module_name, args.name)

    result = {
        "ok": True,
        "class_name": args.name,
        "module": module_name,
        "file": str(target.relative_to(REPO_ROOT)),
        "registered_in": str(REGISTRY_PATH.relative_to(REPO_ROOT)),
        "run_command": f"ros2 run emdb_simulator scene_loader --ros-args -p robot:={args.name}",
        **meta,
    }
    if args.json:
        print(json.dumps(result))
    else:
        print(f"OK: wrote {result['file']}, registered {args.name} in {result['registered_in']}")
        print(f"Try it: {result['run_command']}")
    return 0


def cli_preview(args):
    robots = find_robot_classes()
    robot = find_robot_by_name(robots, args.robot)
    if robot is None:
        print(f"ERROR: No robot named {args.robot!r} found.", file=sys.stderr)
        return 1
    return run_preview(robot)


def build_arg_parser():
    p = argparse.ArgumentParser(description="List, inspect, edit, preview, and create emdb_simulator robots.")
    sub = p.add_subparsers(dest="command")

    sp = sub.add_parser("list", help="List registered robots.")
    sp.add_argument("--json", action="store_true")

    sp = sub.add_parser("inspect", help="Inspect one robot's properties.")
    sp.add_argument("--robot", required=True)
    sp.add_argument("--json", action="store_true")

    sp = sub.add_parser("edit", help="Edit default_gripper or init_qpos on an existing robot.")
    sp.add_argument("--robot", required=True)
    sp.add_argument("--param", required=True, choices=EDITABLE_PROPS)
    sp.add_argument(
        "--value",
        required=True,
        help="New gripper name for default_gripper, or comma-separated floats for init_qpos.",
    )
    sp.add_argument("--json", action="store_true")

    sp = sub.add_parser("create", help="Create a new robot.")
    sp.add_argument("--name", required=True)
    sp.add_argument("--arm", required=True, choices=list(ARMS.keys()))
    sp.add_argument("--base", required=True, choices=[tok for tok, *_ in BASE_CHOICES])
    sp.add_argument("--gripper", required=True, choices=[tok for tok, _ in GRIPPER_CHOICES])
    sp.add_argument("--init-qpos", help="Comma-separated joint angles (radians); omit to use the arm's default.")
    sp.add_argument(
        "--init-torso-qpos", help="Comma-separated torso joint value(s); only meaningful with --base wheeled."
    )
    sp.add_argument("--dry-run", action="store_true")
    sp.add_argument("--json", action="store_true")

    sp = sub.add_parser("preview", help="Open the 3D viewer for a robot (requires `source env.sh` and a display).")
    sp.add_argument("--robot", required=True)

    return p


def main():
    args = build_arg_parser().parse_args()
    if args.command is None:
        run_interactive_menu()
        return
    handlers = {
        "list": cli_list,
        "inspect": cli_inspect,
        "edit": cli_edit,
        "create": cli_create,
        "preview": cli_preview,
    }
    sys.exit(handlers[args.command](args))


if __name__ == "__main__":
    try:
        main()
    except (KeyboardInterrupt, EOFError):
        print("\nBye.")
        sys.exit(0)
